
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'my_new_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

vars:
  load_date: '1992-01-09'
  tpch_size: 1 #1, 10, 100, 1000, 10000
# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  +pre-hook:
    - "{{ auditJobStart() }}"
  +post-hook:
    - "{{ auditJobEnd() }}"
  my_new_project:
    raw_stage:
      tags:
        - 'raw'
      materialized: view
      +schema: "{{env_var('DBT_TGT_SCHEMA') }}"
    stage:
      tags:
        - 'stage'
      enabled: true
      materialized: view
      +schema: "{{env_var('DBT_TGT_SCHEMA') }}"
    raw_vault:
      tags:
        - 'raw_vault'
      materialized: incremental
      +schema: "{{env_var('DBT_TGT_SCHEMA') }}"
      hubs:
        tags:
          - 'hub'
      links:
        tags:
          - 'link'
      sats:
        tags:
          - 'satellite'
      t_links:
        tags:
          - 't_link'
