version: 2

sources:
  - name: tpch_sample
    database: ShreyDBTPOC
    schema: SOURCE_DAY2
    tables:
      - name: LINEITEM
      - name: CUSTOMER
      - name: ORDERS
      - name: PARTSUPP
      - name: SUPPLIER
      - name: PART
      - name: NATION
      - name: REGION


models:
  - name: raw_orders
    columns:
        - name: DISCOUNT
          tests:
            - unique:
                config:            
                  severity: fail
                  store_failures: true